apiVersion: v1
kind: ConfigMap
metadata:
  name: event-app-config
  namespace: event-autoscaling

data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka.kafka.svc.cluster.local:9092"
  TOPIC_NAME: "events-test-2"
  CONSUMER_GROUP: "event-processors-autoscaled-test-2"
  MESSAGES_PER_SECOND: "20"
  BURST_MESSAGES_PER_SECOND: "900"
  BURST_DURATION_SECONDS: "240"
  MESSAGE_SIZE_BYTES: "1024"
  PROCESSING_DELAY_MS: "200"