apiVersion: apps/v1
kind: Deployment

metadata:
  name: producer
  namespace: event-autoscaling

spec:
  replicas: 1

  selector:
    matchLabels:
      app: producer

  template:
    metadata:
      labels:
        app: producer

    spec:
      containers:
      - name: producer
        image: 337462094945.dkr.ecr.us-east-1.amazonaws.com/event-app:eks
        imagePullPolicy: IfNotPresent

        command:
          - python
          - producer.py

        env:
          - name: PYTHONUNBUFFERED
            value: "1"

        envFrom:
          - configMapRef:
              name: event-app-config

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"